apiVersion: v1
kind: Secret
metadata:
  name: smtpd
  labels:
  {{- include "odoo.labels" . | nindent 4 }}
stringData:
  ALLOWED_SENDER_DOMAINS: {{ required "odoo.smtpd.allowedSenderDomains is required"
    .Values.smtpd.allowedSenderDomains | quote }}
  {{ if eq .Values.smtpd.useCloudflareDDNS "1" }}
  CLOUDFLARE_API_KEY: {{ required "odoo.cloudflareApiKey is required" .Values.smtpd.cloudflareApiKey
    | quote }}
  CLOUDFLARE_DNS_RECORDS: {{ required "odoo.cloudflareDnsRecords is required"
    .Values.smtpd.cloudflareDnsRecords | quote }}
  CLOUDFLARE_ZONE_ID: {{ required "odoo.cloudflareZoneId is required" .Values.smtpd.cloudflareZoneId
    | quote }}
  {{ end }}
  DKIM_PRIVATE_KEY: {{ required "odoo.dkimPrivateKey is required" .Values.smtpd.dkimPrivateKey
    | quote }}
  DKIM_SELECTOR: {{ required "odoo.dkimSelector is required" .Values.smtpd.dkimSelector
    | quote }}
  POSTFIX_HOSTNAME: {{ required "odoo.postfixHostname is required" .Values.smtpd.postfixHostname
    | quote }}
  POSTFIX_helo_name: {{ required "odoo.postfixHostname is required" .Values.smtpd.postfixHostname
    | quote }}
  POSTFIX_myhostname: {{ required "odoo.postfixHostname is required" .Values.smtpd.postfixHostname
    | quote }}
type: Opaque