{{ if .Values.cloudflared.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "gitea.labels" . | nindent 4 }}
data:
  {{ .Values.cloudflared.TunnelID | required "Cloudflared TunnelID is required"}}.json: {{ .Values.cloudflared.credentials | toJson | b64enc | quote }}
  credentials.json: {{ .Values.cloudflared.credentials | toJson | b64enc | quote }}
type: Opaque
{{ end }}