{{ if .Values.smtpd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: smtpd
spec:
  type: {{ .Values.smtpd.type | default "ClusterIP" }}
  selector:
    app: smtpd
  ports:
	{{- .Values.smtpd.ports | toYaml | nindent 2 -}}
{{ end }}