{{ if .Values.pgadmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  type: {{ .Values.pgadmin.service.type | default "ClusterIP" }}
  selector:
    app: pgadmin
  ports:
    - port: {{ .Values.pgadmin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{ end }}